### ISSUE TITLE
org.eclipse.jetty.server.Request : java.lang.IllegalStateException: Form is larger than max length 200000

### ISSUE THREAD

**Issue by tehsven** [adobe/S3Mock#1502]
I'm getting this error in the s3mock logs when attempting to upload a file

> 2023-11-29 15:17:34 2023-11-29T23:17:34.068Z  WARN 1 --- [qtp975033189-36] org.eclipse.jetty.server.Request         : java.lang.IllegalStateException: Form is larger than max length 200000

I'm on s3mock version 3.1.0.

Ideally I'd be able to set a jetty parameter to increase the max form size, but I haven't been able to figure how out to do so.

I'm using the docker image and tried setting

> entrypoint: ["java", "-Dorg.eclipse.jetty.server.Request.maxFormContentSize=99900000", "-Djava.security.egd=file:/dev/./urandom", "-jar", "s3mock.jar"]

Relevant section from our docker-compose file:
```
  s3mock:
    container_name: s3mock
    image: adobe/s3mock:3.1.0
    environment:
      - retainFilesOnExit=true
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./s3mock:/s3mockroot
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:9090"]
```
