### ISSUE TITLE
Persistent data/storage and mount volume

### ISSUE THREAD

**Issue by nwesthoff** [adobe/S3Mock#200]
S3Mock creates a new `s3mockFileStore<number>` folder each time the container starts. When using the container for local development this means all data is lost when I restart/recreate the container, or even restart Docker engine (on Mac OS).

I haven't seen anything in the README, but would it be possible to mount a volume and reuse a store if it exists?

current docker-compose for good measure:
```yaml
s3mock:
        container_name: hr-s3mock
        image: adobe/s3mock
        restart: unless-stopped
        tty: true
        ports:
            - 9090:9090
            - 9191:9191
        environment:
            - initialBuckets=${S3_BUCKET}
            - validKmsKeys=${S3_ACCESSKEY_SECRET}
```

**Comment by Alain-Bearez** [comment]
Do you mean something like the following?

```
  s3local:
    image: adobe/s3mock:2.1.7
    ports:
      - 9090
    environment:
      - initialBuckets=default
      - root=/data
    volumes:
      - ./data/s3:/data:cached
``` 

And then having a folder hierarchy under ` ./data/s3/default/` ?
