### ISSUE TITLE
ETag missing for multipart AWS SDK ManagedUploads

### ISSUE THREAD

**Issue by mbalc** [adobe/S3Mock#843]
https://www.loom.com/share/1bf4fca190db4444ad87e23be8992719

test case:
- write the following to `docker-compose.yaml`:
```
services:
  localstack:
    # v2.5 breaks persistence
    # issue is being tracked: https://github.com/adobe/S3Mock/issues/818
    image: adobe/s3mock:2.7.1
    container_name: ${APP_NAME}-localstack
    ports:
      - "4566:9090"
    environment:
      # - retainFilesOnExit=true
      - initialBuckets=my-bucket
```
- write the following to `test.html`:
```
<link
  rel="stylesheet"
  href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css"
  type="text/css"
/>
<script src="https://sdk.amazonaws.com/js/aws-sdk-2.410.0.min.js"></script>


<form id="dropzone" class="dropzone" action="/"></form>

<button id="upload">Upload</button>


<script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>
<script>
  document.getElementById("upload").addEventListener("click", () => {
    let file = document.getElementById("dropzone").dropzone.files[0]
    console.info(file)

    const s3 = new AWS.S3({
      accessKeyId: "laa",
      secretAccessKey: "laa",
      // region: "laaa",
      Credential: {
        accessKeyId: "laa",
        secretAccessKey: "laa",
      },

      endpoint: "http://localhost:4566",
    });

    s3.upload(
      {
        Bucket: "my-bucket",
        Key: "my-bucket/model.zip",
        Body: file,
      },
      (err, data) => {
        if (err) console.log("An error occurred", err);
        console.log("Uploaded the file at", data.Location);
      }
    );
  });
</script>
```
- run `docker compose up localstack`
- run `docker run -it -v /home/mbalc/Documents/repos/autodl:/usr/share/nginx/html -p 80:80 nginx`

- visit `http://localhost/test.html` with your browser
- open devtools console to monitor logs
- select some bigger (+10MB) file in the dropzone (doesn't matter, I used https://tfhub.dev/adityakane2001/regnety800mf_feature_extractor/1)
- click upload

Expected: 
- upload happily goes through

What actually happens: 
- SDK raises an error: 
```
An error occurred ETagMissing: No access to ETag property on response. Check CORS configuration to expose ETag header.
```
